[BB-05] Responsive website
ipsa-scrypt/big-brain pull request #4
Opened 2023-10-27 18:05 UTC by KreatorOf

Context:  background-color doesn't fit screen when resize on my side.

Youtrack: [BB-05](https://irisrobotics.youtrack.cloud/issue/PMI-34)

2023-10-28 05:39 UTC, PhantHive requested changes

2023-10-28 05:39 UTC, PhantHive commented on src/App.css
> +	margin-top: -100px; /* Adjust margin for more space */
Hmmm, are you sure this was needed?

2023-10-28 05:40 UTC, PhantHive commented on src/App.css
> +	margin-top: -100px; /* Adjust margin for more space */
I think we could avoid that along the CSS by using more flex box

2023-10-31 20:42 UTC, KreatorOf commented
I add an AI response field, check the code and we can merge on main and delete this branch ! ;)

YouTrack: [BB-06](https://irisrobotics.youtrack.cloud/issue/PMI-39)

2023-11-01 11:45 UTC, PhantHive commented
We cannot merge this branch until it's fully responsive :|

2023-11-01 12:02 UTC, PhantHive requested changes
Add the  media section  and adapt it to fits the need of the mobile version.

2023-11-01 12:02 UTC, PhantHive commented on src/App.css
>  }
Add a media section for phones

```css
@media screen and (max-width: 800px) {
	.title-slogan {
		display: grid;
		grid-column: 1 / span 4;
		align-items: center;
		justify-content: center;
		gap: 20px;
	}
	.bb-title {
		color: #FFF;
		font-size: 55px; 
		font-style: normal;
		line-height: normal;
		text-align: center;
	}
	.slogan {
		color: #C6C8DF;
		font-size: 23px; 
		font-style: normal;
		line-height: normal;
		text-align: center;
	}
}
```

2023-11-14 07:43 UTC, PhantHive approved these changes

2023-11-14 07:43 UTC, PhantHive commented on src/components/output.tsx
> +export function Outputs({ submittedRequest }: { submittedRequest: string }) {
Should be const arrow function ☀️🥹

2023-11-17 19:12 UTC, PhantHive approved these changes
Approved.

2023-11-17 19:37 UTC, merged